class NecklaceExecuter
{
	public static void main(String[] args)
	{


		Necklace n1=new Necklace();
		n1.brand="Tanishq";
		n1.color="Gold";
		n1.material="Gold";
		n1.price=50000;
		n1.weight=25;
		n1.size="Long";
		n1.design="Floral";
		n1.adjustable=true;
		n1.stones=10;
		n1.type="Chain";
		n1.origin="India";
		n1.finish="Glossy";
		n1.style="Traditional";
		n1.gender="Female";
		n1.claspType="Hook";
		n1.plating="Gold";
		n1.durability="High";
		n1.usage="Wedding";
		n1.warranty="2 years";
		n1.manufacturer="Tanishq Ltd";

		System.out.println("Brand: "+n1.brand);
		System.out.println("Color: "+n1.color);
		System.out.println("Material: "+n1.material);
		System.out.println("Price: "+n1.price);
		System.out.println("Weight: "+n1.weight);
		System.out.println("Size: "+n1.size);
		System.out.println("Design: "+n1.design);
		System.out.println("Adjustable: "+n1.adjustable);
		System.out.println("Stones: "+n1.stones);
		System.out.println("Type: "+n1.type);
		System.out.println("Origin: "+n1.origin);
		System.out.println("Finish: "+n1.finish);
		System.out.println("Style: "+n1.style);
		System.out.println("Gender: "+n1.gender);
		System.out.println("Clasp Type: "+n1.claspType);
		System.out.println("Plating: "+n1.plating);
		System.out.println("Durability: "+n1.durability);
		System.out.println("Usage: "+n1.usage);
		System.out.println("Warranty: "+n1.warranty);
		System.out.println("Manufacturer: "+n1.manufacturer+"\n");


		Necklace n2=new Necklace();
		n2.brand="Malabar";
		n2.color="Silver";
		n2.material="Silver";
		n2.price=30000;
		n2.weight=20;
		n2.size="Medium";
		n2.design="Leaf";
		n2.adjustable=true;
		n2.stones=6;
		n2.type="Chain";
		n2.origin="India";
		n2.finish="Matte";
		n2.style="Modern";
		n2.gender="Female";
		n2.claspType="Hook";
		n2.plating="Silver";
		n2.durability="Medium";
		n2.usage="Party";
		n2.warranty="1 year";
		n2.manufacturer="Malabar Ltd";

		System.out.println("Brand: "+n2.brand);
		System.out.println("Color: "+n2.color);
		System.out.println("Material: "+n2.material);
		System.out.println("Price: "+n2.price);
		System.out.println("Weight: "+n2.weight);
		System.out.println("Size: "+n2.size);
		System.out.println("Design: "+n2.design);
		System.out.println("Adjustable: "+n2.adjustable);
		System.out.println("Stones: "+n2.stones);
		System.out.println("Type: "+n2.type);
		System.out.println("Origin: "+n2.origin);
		System.out.println("Finish: "+n2.finish);
		System.out.println("Style: "+n2.style);
		System.out.println("Gender: "+n2.gender);
		System.out.println("Clasp Type: "+n2.claspType);
		System.out.println("Plating: "+n2.plating);
		System.out.println("Durability: "+n2.durability);
		System.out.println("Usage: "+n2.usage);
		System.out.println("Warranty: "+n2.warranty);
		System.out.println("Manufacturer: "+n2.manufacturer+"\n");
		
		Necklace n3=new Necklace();
n3.brand="Kalyan";
n3.color="Rose Gold";
n3.material="Gold";
n3.price=45000;
n3.weight=22;
n3.size="Long";
n3.design="Heart";
n3.adjustable=true;
n3.stones=8;
n3.type="Chain";
n3.origin="India";
n3.finish="Glossy";
n3.style="Modern";
n3.gender="Female";
n3.claspType="Hook";
n3.plating="Rose Gold";
n3.durability="High";
n3.usage="Casual";
n3.warranty="2 years";
n3.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n3.brand);
System.out.println("Color: "+n3.color);
System.out.println("Material: "+n3.material);
System.out.println("Price: "+n3.price);
System.out.println("Weight: "+n3.weight);
System.out.println("Size: "+n3.size);
System.out.println("Design: "+n3.design);
System.out.println("Adjustable: "+n3.adjustable);
System.out.println("Stones: "+n3.stones);
System.out.println("Type: "+n3.type);
System.out.println("Origin: "+n3.origin);
System.out.println("Finish: "+n3.finish);
System.out.println("Style: "+n3.style);
System.out.println("Gender: "+n3.gender);
System.out.println("Clasp Type: "+n3.claspType);
System.out.println("Plating: "+n3.plating);
System.out.println("Durability: "+n3.durability);
System.out.println("Usage: "+n3.usage);
System.out.println("Warranty: "+n3.warranty);
System.out.println("Manufacturer: "+n3.manufacturer+"\n");


Necklace n4=new Necklace();
n4.brand="PC Jeweller";
n4.color="Silver";
n4.material="Silver";
n4.price=28000;
n4.weight=18;
n4.size="Medium";
n4.design="Star";
n4.adjustable=true;
n4.stones=5;
n4.type="Chain";
n4.origin="India";
n4.finish="Matte";
n4.style="Modern";
n4.gender="Female";
n4.claspType="Hook";
n4.plating="Silver";
n4.durability="Medium";
n4.usage="Daily";
n4.warranty="1 year";
n4.manufacturer="PC Jeweller";

System.out.println("Brand: "+n4.brand);
System.out.println("Color: "+n4.color);
System.out.println("Material: "+n4.material);
System.out.println("Price: "+n4.price);
System.out.println("Weight: "+n4.weight);
System.out.println("Size: "+n4.size);
System.out.println("Design: "+n4.design);
System.out.println("Adjustable: "+n4.adjustable);
System.out.println("Stones: "+n4.stones);
System.out.println("Type: "+n4.type);
System.out.println("Origin: "+n4.origin);
System.out.println("Finish: "+n4.finish);
System.out.println("Style: "+n4.style);
System.out.println("Gender: "+n4.gender);
System.out.println("Clasp Type: "+n4.claspType);
System.out.println("Plating: "+n4.plating);
System.out.println("Durability: "+n4.durability);
System.out.println("Usage: "+n4.usage);
System.out.println("Warranty: "+n4.warranty);
System.out.println("Manufacturer: "+n4.manufacturer+"\n");


Necklace n5=new Necklace();
n5.brand="Tanishq";
n5.color="Gold";
n5.material="Gold";
n5.price=52000;
n5.weight=26;
n5.size="Long";
n5.design="Floral";
n5.adjustable=false;
n5.stones=12;
n5.type="Bangle Chain";
n5.origin="India";
n5.finish="Glossy";
n5.style="Traditional";
n5.gender="Female";
n5.claspType="Lock";
n5.plating="Gold";
n5.durability="High";
n5.usage="Wedding";
n5.warranty="3 years";
n5.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n5.brand);
System.out.println("Color: "+n5.color);
System.out.println("Material: "+n5.material);
System.out.println("Price: "+n5.price);
System.out.println("Weight: "+n5.weight);
System.out.println("Size: "+n5.size);
System.out.println("Design: "+n5.design);
System.out.println("Adjustable: "+n5.adjustable);
System.out.println("Stones: "+n5.stones);
System.out.println("Type: "+n5.type);
System.out.println("Origin: "+n5.origin);
System.out.println("Finish: "+n5.finish);
System.out.println("Style: "+n5.style);
System.out.println("Gender: "+n5.gender);
System.out.println("Clasp Type: "+n5.claspType);
System.out.println("Plating: "+n5.plating);
System.out.println("Durability: "+n5.durability);
System.out.println("Usage: "+n5.usage);
System.out.println("Warranty: "+n5.warranty);
System.out.println("Manufacturer: "+n5.manufacturer+"\n");

Necklace n6=new Necklace();
n6.brand="Malabar";
n6.color="Silver";
n6.material="Silver";
n6.price=32000;
n6.weight=21;
n6.size="Medium";
n6.design="Leaf";
n6.adjustable=true;
n6.stones=7;
n6.type="Chain";
n6.origin="India";
n6.finish="Matte";
n6.style="Modern";
n6.gender="Female";
n6.claspType="Hook";
n6.plating="Silver";
n6.durability="Medium";
n6.usage="Party";
n6.warranty="1 year";
n6.manufacturer="Malabar Ltd";

System.out.println("Brand: "+n6.brand);
System.out.println("Color: "+n6.color);
System.out.println("Material: "+n6.material);
System.out.println("Price: "+n6.price);
System.out.println("Weight: "+n6.weight);
System.out.println("Size: "+n6.size);
System.out.println("Design: "+n6.design);
System.out.println("Adjustable: "+n6.adjustable);
System.out.println("Stones: "+n6.stones);
System.out.println("Type: "+n6.type);
System.out.println("Origin: "+n6.origin);
System.out.println("Finish: "+n6.finish);
System.out.println("Style: "+n6.style);
System.out.println("Gender: "+n6.gender);
System.out.println("Clasp Type: "+n6.claspType);
System.out.println("Plating: "+n6.plating);
System.out.println("Durability: "+n6.durability);
System.out.println("Usage: "+n6.usage);
System.out.println("Warranty: "+n6.warranty);
System.out.println("Manufacturer: "+n6.manufacturer+"\n");


Necklace n7=new Necklace();
n7.brand="Kalyan";
n7.color="Rose Gold";
n7.material="Gold";
n7.price=47000;
n7.weight=23;
n7.size="Long";
n7.design="Heart";
n7.adjustable=true;
n7.stones=9;
n7.type="Chain";
n7.origin="India";
n7.finish="Glossy";
n7.style="Modern";
n7.gender="Female";
n7.claspType="Hook";
n7.plating="Rose Gold";
n7.durability="High";
n7.usage="Casual";
n7.warranty="2 years";
n7.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n7.brand);
System.out.println("Color: "+n7.color);
System.out.println("Material: "+n7.material);
System.out.println("Price: "+n7.price);
System.out.println("Weight: "+n7.weight);
System.out.println("Size: "+n7.size);
System.out.println("Design: "+n7.design);
System.out.println("Adjustable: "+n7.adjustable);
System.out.println("Stones: "+n7.stones);
System.out.println("Type: "+n7.type);
System.out.println("Origin: "+n7.origin);
System.out.println("Finish: "+n7.finish);
System.out.println("Style: "+n7.style);
System.out.println("Gender: "+n7.gender);
System.out.println("Clasp Type: "+n7.claspType);
System.out.println("Plating: "+n7.plating);
System.out.println("Durability: "+n7.durability);
System.out.println("Usage: "+n7.usage);
System.out.println("Warranty: "+n7.warranty);
System.out.println("Manufacturer: "+n7.manufacturer+"\n");


Necklace n8=new Necklace();
n8.brand="PC Jeweller";
n8.color="Silver";
n8.material="Silver";
n8.price=29000;
n8.weight=19;
n8.size="Medium";
n8.design="Star";
n8.adjustable=true;
n8.stones=6;
n8.type="Chain";
n8.origin="India";
n8.finish="Matte";
n8.style="Modern";
n8.gender="Female";
n8.claspType="Hook";
n8.plating="Silver";
n8.durability="Medium";
n8.usage="Daily";
n8.warranty="1 year";
n8.manufacturer="PC Jeweller";

System.out.println("Brand: "+n8.brand);
System.out.println("Color: "+n8.color);
System.out.println("Material: "+n8.material);
System.out.println("Price: "+n8.price);
System.out.println("Weight: "+n8.weight);
System.out.println("Size: "+n8.size);
System.out.println("Design: "+n8.design);
System.out.println("Adjustable: "+n8.adjustable);
System.out.println("Stones: "+n8.stones);
System.out.println("Type: "+n8.type);
System.out.println("Origin: "+n8.origin);
System.out.println("Finish: "+n8.finish);
System.out.println("Style: "+n8.style);
System.out.println("Gender: "+n8.gender);
System.out.println("Clasp Type: "+n8.claspType);
System.out.println("Plating: "+n8.plating);
System.out.println("Durability: "+n8.durability);
System.out.println("Usage: "+n8.usage);
System.out.println("Warranty: "+n8.warranty);
System.out.println("Manufacturer: "+n8.manufacturer+"\n");


Necklace n9=new Necklace();
n9.brand="Tanishq";
n9.color="Gold";
n9.material="Gold";
n9.price=54000;
n9.weight=27;
n9.size="Long";
n9.design="Floral";
n9.adjustable=false;
n9.stones=13;
n9.type="Chain";
n9.origin="India";
n9.finish="Glossy";
n9.style="Traditional";
n9.gender="Female";
n9.claspType="Lock";
n9.plating="Gold";
n9.durability="High";
n9.usage="Wedding";
n9.warranty="3 years";
n9.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n9.brand);
System.out.println("Color: "+n9.color);
System.out.println("Material: "+n9.material);
System.out.println("Price: "+n9.price);
System.out.println("Weight: "+n9.weight);
System.out.println("Size: "+n9.size);
System.out.println("Design: "+n9.design);
System.out.println("Adjustable: "+n9.adjustable);
System.out.println("Stones: "+n9.stones);
System.out.println("Type: "+n9.type);
System.out.println("Origin: "+n9.origin);
System.out.println("Finish: "+n9.finish);
System.out.println("Style: "+n9.style);
System.out.println("Gender: "+n9.gender);
System.out.println("Clasp Type: "+n9.claspType);
System.out.println("Plating: "+n9.plating);
System.out.println("Durability: "+n9.durability);
System.out.println("Usage: "+n9.usage);
System.out.println("Warranty: "+n9.warranty);
System.out.println("Manufacturer: "+n9.manufacturer+"\n");


Necklace n10=new Necklace();
n10.brand="Malabar";
n10.color="Silver";
n10.material="Silver";
n10.price=34000;
n10.weight=22;
n10.size="Medium";
n10.design="Leaf";
n10.adjustable=true;
n10.stones=8;
n10.type="Chain";
n10.origin="India";
n10.finish="Matte";
n10.style="Modern";
n10.gender="Female";
n10.claspType="Hook";
n10.plating="Silver";
n10.durability="Medium";
n10.usage="Party";
n10.warranty="1 year";
n10.manufacturer="Malabar Ltd";

System.out.println("Brand: "+n10.brand);
System.out.println("Color: "+n10.color);
System.out.println("Material: "+n10.material);
System.out.println("Price: "+n10.price);
System.out.println("Weight: "+n10.weight);
System.out.println("Size: "+n10.size);
System.out.println("Design: "+n10.design);
System.out.println("Adjustable: "+n10.adjustable);
System.out.println("Stones: "+n10.stones);
System.out.println("Type: "+n10.type);
System.out.println("Origin: "+n10.origin);
System.out.println("Finish: "+n10.finish);
System.out.println("Style: "+n10.style);
System.out.println("Gender: "+n10.gender);
System.out.println("Clasp Type: "+n10.claspType);
System.out.println("Plating: "+n10.plating);
System.out.println("Durability: "+n10.durability);
System.out.println("Usage: "+n10.usage);
System.out.println("Warranty: "+n10.warranty);
System.out.println("Manufacturer: "+n10.manufacturer+"\n");

Necklace n11=new Necklace();
n11.brand="Kalyan";
n11.color="Rose Gold";
n11.material="Gold";
n11.price=46000;
n11.weight=23;
n11.size="Long";
n11.design="Heart";
n11.adjustable=true;
n11.stones=9;
n11.type="Chain";
n11.origin="India";
n11.finish="Glossy";
n11.style="Modern";
n11.gender="Female";
n11.claspType="Hook";
n11.plating="Rose Gold";
n11.durability="High";
n11.usage="Casual";
n11.warranty="2 years";
n11.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n11.brand);
System.out.println("Color: "+n11.color);
System.out.println("Material: "+n11.material);
System.out.println("Price: "+n11.price);
System.out.println("Weight: "+n11.weight);
System.out.println("Size: "+n11.size);
System.out.println("Design: "+n11.design);
System.out.println("Adjustable: "+n11.adjustable);
System.out.println("Stones: "+n11.stones);
System.out.println("Type: "+n11.type);
System.out.println("Origin: "+n11.origin);
System.out.println("Finish: "+n11.finish);
System.out.println("Style: "+n11.style);
System.out.println("Gender: "+n11.gender);
System.out.println("Clasp Type: "+n11.claspType);
System.out.println("Plating: "+n11.plating);
System.out.println("Durability: "+n11.durability);
System.out.println("Usage: "+n11.usage);
System.out.println("Warranty: "+n11.warranty);
System.out.println("Manufacturer: "+n11.manufacturer+"\n");


Necklace n12=new Necklace();
n12.brand="PC Jeweller";
n12.color="Silver";
n12.material="Silver";
n12.price=30000;
n12.weight=20;
n12.size="Medium";
n12.design="Star";
n12.adjustable=true;
n12.stones=7;
n12.type="Chain";
n12.origin="India";
n12.finish="Matte";
n12.style="Modern";
n12.gender="Female";
n12.claspType="Hook";
n12.plating="Silver";
n12.durability="Medium";
n12.usage="Daily";
n12.warranty="1 year";
n12.manufacturer="PC Jeweller";

System.out.println("Brand: "+n12.brand);
System.out.println("Color: "+n12.color);
System.out.println("Material: "+n12.material);
System.out.println("Price: "+n12.price);
System.out.println("Weight: "+n12.weight);
System.out.println("Size: "+n12.size);
System.out.println("Design: "+n12.design);
System.out.println("Adjustable: "+n12.adjustable);
System.out.println("Stones: "+n12.stones);
System.out.println("Type: "+n12.type);
System.out.println("Origin: "+n12.origin);
System.out.println("Finish: "+n12.finish);
System.out.println("Style: "+n12.style);
System.out.println("Gender: "+n12.gender);
System.out.println("Clasp Type: "+n12.claspType);
System.out.println("Plating: "+n12.plating);
System.out.println("Durability: "+n12.durability);
System.out.println("Usage: "+n12.usage);
System.out.println("Warranty: "+n12.warranty);
System.out.println("Manufacturer: "+n12.manufacturer+"\n");


Necklace n13=new Necklace();
n13.brand="Tanishq";
n13.color="Gold";
n13.material="Gold";
n13.price=55000;
n13.weight=28;
n13.size="Long";
n13.design="Floral";
n13.adjustable=false;
n13.stones=14;
n13.type="Chain";
n13.origin="India";
n13.finish="Glossy";
n13.style="Traditional";
n13.gender="Female";
n13.claspType="Lock";
n13.plating="Gold";
n13.durability="High";
n13.usage="Wedding";
n13.warranty="3 years";
n13.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n13.brand);
System.out.println("Color: "+n13.color);
System.out.println("Material: "+n13.material);
System.out.println("Price: "+n13.price);
System.out.println("Weight: "+n13.weight);
System.out.println("Size: "+n13.size);
System.out.println("Design: "+n13.design);
System.out.println("Adjustable: "+n13.adjustable);
System.out.println("Stones: "+n13.stones);
System.out.println("Type: "+n13.type);
System.out.println("Origin: "+n13.origin);
System.out.println("Finish: "+n13.finish);
System.out.println("Style: "+n13.style);
System.out.println("Gender: "+n13.gender);
System.out.println("Clasp Type: "+n13.claspType);
System.out.println("Plating: "+n13.plating);
System.out.println("Durability: "+n13.durability);
System.out.println("Usage: "+n13.usage);
System.out.println("Warranty: "+n13.warranty);
System.out.println("Manufacturer: "+n13.manufacturer+"\n");


Necklace n14=new Necklace();
n14.brand="Malabar";
n14.color="Silver";
n14.material="Silver";
n14.price=33000;
n14.weight=21;
n14.size="Medium";
n14.design="Leaf";
n14.adjustable=true;
n14.stones=8;
n14.type="Chain";
n14.origin="India";
n14.finish="Matte";
n14.style="Modern";
n14.gender="Female";
n14.claspType="Hook";
n14.plating="Silver";
n14.durability="Medium";
n14.usage="Party";
n14.warranty="1 year";
n14.manufacturer="Malabar Ltd";

System.out.println("Brand: "+n14.brand);
System.out.println("Color: "+n14.color);
System.out.println("Material: "+n14.material);
System.out.println("Price: "+n14.price);
System.out.println("Weight: "+n14.weight);
System.out.println("Size: "+n14.size);
System.out.println("Design: "+n14.design);
System.out.println("Adjustable: "+n14.adjustable);
System.out.println("Stones: "+n14.stones);
System.out.println("Type: "+n14.type);
System.out.println("Origin: "+n14.origin);
System.out.println("Finish: "+n14.finish);
System.out.println("Style: "+n14.style);
System.out.println("Gender: "+n14.gender);
System.out.println("Clasp Type: "+n14.claspType);
System.out.println("Plating: "+n14.plating);
System.out.println("Durability: "+n14.durability);
System.out.println("Usage: "+n14.usage);
System.out.println("Warranty: "+n14.warranty);
System.out.println("Manufacturer: "+n14.manufacturer+"\n");


Necklace n15=new Necklace();
n15.brand="Kalyan";
n15.color="Rose Gold";
n15.material="Gold";
n15.price=48000;
n15.weight=24;
n15.size="Long";
n15.design="Heart";
n15.adjustable=true;
n15.stones=10;
n15.type="Chain";
n15.origin="India";
n15.finish="Glossy";
n15.style="Modern";
n15.gender="Female";
n15.claspType="Hook";
n15.plating="Rose Gold";
n15.durability="High";
n15.usage="Casual";
n15.warranty="2 years";
n15.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n15.brand);
System.out.println("Color: "+n15.color);
System.out.println("Material: "+n15.material);
System.out.println("Price: "+n15.price);
System.out.println("Weight: "+n15.weight);
System.out.println("Size: "+n15.size);
System.out.println("Design: "+n15.design);
System.out.println("Adjustable: "+n15.adjustable);
System.out.println("Stones: "+n15.stones);
System.out.println("Type: "+n15.type);
System.out.println("Origin: "+n15.origin);
System.out.println("Finish: "+n15.finish);
System.out.println("Style: "+n15.style);
System.out.println("Gender: "+n15.gender);
System.out.println("Clasp Type: "+n15.claspType);
System.out.println("Plating: "+n15.plating);
System.out.println("Durability: "+n15.durability);
System.out.println("Usage: "+n15.usage);
System.out.println("Warranty: "+n15.warranty);
System.out.println("Manufacturer: "+n15.manufacturer+"\n");

Necklace n16=new Necklace();
n16.brand="PC Jeweller";
n16.color="Silver";
n16.material="Silver";
n16.price=31000;
n16.weight=21;
n16.size="Medium";
n16.design="Star";
n16.adjustable=true;
n16.stones=6;
n16.type="Chain";
n16.origin="India";
n16.finish="Matte";
n16.style="Modern";
n16.gender="Female";
n16.claspType="Hook";
n16.plating="Silver";
n16.durability="Medium";
n16.usage="Daily";
n16.warranty="1 year";
n16.manufacturer="PC Jeweller";

System.out.println("Brand: "+n16.brand);
System.out.println("Color: "+n16.color);
System.out.println("Material: "+n16.material);
System.out.println("Price: "+n16.price);
System.out.println("Weight: "+n16.weight);
System.out.println("Size: "+n16.size);
System.out.println("Design: "+n16.design);
System.out.println("Adjustable: "+n16.adjustable);
System.out.println("Stones: "+n16.stones);
System.out.println("Type: "+n16.type);
System.out.println("Origin: "+n16.origin);
System.out.println("Finish: "+n16.finish);
System.out.println("Style: "+n16.style);
System.out.println("Gender: "+n16.gender);
System.out.println("Clasp Type: "+n16.claspType);
System.out.println("Plating: "+n16.plating);
System.out.println("Durability: "+n16.durability);
System.out.println("Usage: "+n16.usage);
System.out.println("Warranty: "+n16.warranty);
System.out.println("Manufacturer: "+n16.manufacturer+"\n");


Necklace n17=new Necklace();
n17.brand="Tanishq";
n17.color="Gold";
n17.material="Gold";
n17.price=56000;
n17.weight=29;
n17.size="Long";
n17.design="Floral";
n17.adjustable=false;
n17.stones=15;
n17.type="Chain";
n17.origin="India";
n17.finish="Glossy";
n17.style="Traditional";
n17.gender="Female";
n17.claspType="Lock";
n17.plating="Gold";
n17.durability="High";
n17.usage="Wedding";
n17.warranty="3 years";
n17.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n17.brand);
System.out.println("Color: "+n17.color);
System.out.println("Material: "+n17.material);
System.out.println("Price: "+n17.price);
System.out.println("Weight: "+n17.weight);
System.out.println("Size: "+n17.size);
System.out.println("Design: "+n17.design);
System.out.println("Adjustable: "+n17.adjustable);
System.out.println("Stones: "+n17.stones);
System.out.println("Type: "+n17.type);
System.out.println("Origin: "+n17.origin);
System.out.println("Finish: "+n17.finish);
System.out.println("Style: "+n17.style);
System.out.println("Gender: "+n17.gender);
System.out.println("Clasp Type: "+n17.claspType);
System.out.println("Plating: "+n17.plating);
System.out.println("Durability: "+n17.durability);
System.out.println("Usage: "+n17.usage);
System.out.println("Warranty: "+n17.warranty);
System.out.println("Manufacturer: "+n17.manufacturer+"\n");


Necklace n18=new Necklace();
n18.brand="Malabar";
n18.color="Silver";
n18.material="Silver";
n18.price=35000;
n18.weight=23;
n18.size="Medium";
n18.design="Leaf";
n18.adjustable=true;
n18.stones=9;
n18.type="Chain";
n18.origin="India";
n18.finish="Matte";
n18.style="Modern";
n18.gender="Female";
n18.claspType="Hook";
n18.plating="Silver";
n18.durability="Medium";
n18.usage="Party";
n18.warranty="1 year";
n18.manufacturer="Malabar Ltd";

System.out.println("Brand: "+n18.brand);
System.out.println("Color: "+n18.color);
System.out.println("Material: "+n18.material);
System.out.println("Price: "+n18.price);
System.out.println("Weight: "+n18.weight);
System.out.println("Size: "+n18.size);
System.out.println("Design: "+n18.design);
System.out.println("Adjustable: "+n18.adjustable);
System.out.println("Stones: "+n18.stones);
System.out.println("Type: "+n18.type);
System.out.println("Origin: "+n18.origin);
System.out.println("Finish: "+n18.finish);
System.out.println("Style: "+n18.style);
System.out.println("Gender: "+n18.gender);
System.out.println("Clasp Type: "+n18.claspType);
System.out.println("Plating: "+n18.plating);
System.out.println("Durability: "+n18.durability);
System.out.println("Usage: "+n18.usage);
System.out.println("Warranty: "+n18.warranty);
System.out.println("Manufacturer: "+n18.manufacturer+"\n");


Necklace n19=new Necklace();
n19.brand="Kalyan";
n19.color="Rose Gold";
n19.material="Gold";
n19.price=49000;
n19.weight=25;
n19.size="Long";
n19.design="Heart";
n19.adjustable=true;
n19.stones=11;
n19.type="Chain";
n19.origin="India";
n19.finish="Glossy";
n19.style="Modern";
n19.gender="Female";
n19.claspType="Hook";
n19.plating="Rose Gold";
n19.durability="High";
n19.usage="Casual";
n19.warranty="2 years";
n19.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n19.brand);
System.out.println("Color: "+n19.color);
System.out.println("Material: "+n19.material);
System.out.println("Price: "+n19.price);
System.out.println("Weight: "+n19.weight);
System.out.println("Size: "+n19.size);
System.out.println("Design: "+n19.design);
System.out.println("Adjustable: "+n19.adjustable);
System.out.println("Stones: "+n19.stones);
System.out.println("Type: "+n19.type);
System.out.println("Origin: "+n19.origin);
System.out.println("Finish: "+n19.finish);
System.out.println("Style: "+n19.style);
System.out.println("Gender: "+n19.gender);
System.out.println("Clasp Type: "+n19.claspType);
System.out.println("Plating: "+n19.plating);
System.out.println("Durability: "+n19.durability);
System.out.println("Usage: "+n19.usage);
System.out.println("Warranty: "+n19.warranty);
System.out.println("Manufacturer: "+n19.manufacturer+"\n");


Necklace n20=new Necklace();
n20.brand="Tanishq";
n20.color="Gold";
n20.material="Gold";
n20.price=58000;
n20.weight=30;
n20.size="Long";
n20.design="Floral";
n20.adjustable=false;
n20.stones=16;
n20.type="Chain";
n20.origin="India";
n20.finish="Glossy";
n20.style="Traditional";
n20.gender="Female";
n20.claspType="Lock";
n20.plating="Gold";
n20.durability="High";
n20.usage="Wedding";
n20.warranty="3 years";
n20.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n20.brand);
System.out.println("Color: "+n20.color);
System.out.println("Material: "+n20.material);
System.out.println("Price: "+n20.price);
System.out.println("Weight: "+n20.weight);
System.out.println("Size: "+n20.size);
System.out.println("Design: "+n20.design);
System.out.println("Adjustable: "+n20.adjustable);
System.out.println("Stones: "+n20.stones);
System.out.println("Type: "+n20.type);
System.out.println("Origin: "+n20.origin);
System.out.println("Finish: "+n20.finish);
System.out.println("Style: "+n20.style);
System.out.println("Gender: "+n20.gender);
System.out.println("Clasp Type: "+n20.claspType);
System.out.println("Plating: "+n20.plating);
System.out.println("Durability: "+n20.durability);
System.out.println("Usage: "+n20.usage);
System.out.println("Warranty: "+n20.warranty);
System.out.println("Manufacturer: "+n20.manufacturer+"\n");

Necklace n21=new Necklace();
n21.brand="Malabar";
n21.color="Silver";
n21.material="Silver";
n21.price=36000;
n21.weight=24;
n21.size="Medium";
n21.design="Leaf";
n21.adjustable=true;
n21.stones=10;
n21.type="Chain";
n21.origin="India";
n21.finish="Matte";
n21.style="Modern";
n21.gender="Female";
n21.claspType="Hook";
n21.plating="Silver";
n21.durability="Medium";
n21.usage="Party";
n21.warranty="1 year";
n21.manufacturer="Malabar Ltd";

System.out.println("Brand: "+n21.brand);
System.out.println("Color: "+n21.color);
System.out.println("Material: "+n21.material);
System.out.println("Price: "+n21.price);
System.out.println("Weight: "+n21.weight);
System.out.println("Size: "+n21.size);
System.out.println("Design: "+n21.design);
System.out.println("Adjustable: "+n21.adjustable);
System.out.println("Stones: "+n21.stones);
System.out.println("Type: "+n21.type);
System.out.println("Origin: "+n21.origin);
System.out.println("Finish: "+n21.finish);
System.out.println("Style: "+n21.style);
System.out.println("Gender: "+n21.gender);
System.out.println("Clasp Type: "+n21.claspType);
System.out.println("Plating: "+n21.plating);
System.out.println("Durability: "+n21.durability);
System.out.println("Usage: "+n21.usage);
System.out.println("Warranty: "+n21.warranty);
System.out.println("Manufacturer: "+n21.manufacturer+"\n");


Necklace n22=new Necklace();
n22.brand="Kalyan";
n22.color="Rose Gold";
n22.material="Gold";
n22.price=50000;
n22.weight=26;
n22.size="Long";
n22.design="Heart";
n22.adjustable=true;
n22.stones=12;
n22.type="Chain";
n22.origin="India";
n22.finish="Glossy";
n22.style="Modern";
n22.gender="Female";
n22.claspType="Hook";
n22.plating="Rose Gold";
n22.durability="High";
n22.usage="Casual";
n22.warranty="2 years";
n22.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n22.brand);
System.out.println("Color: "+n22.color);
System.out.println("Material: "+n22.material);
System.out.println("Price: "+n22.price);
System.out.println("Weight: "+n22.weight);
System.out.println("Size: "+n22.size);
System.out.println("Design: "+n22.design);
System.out.println("Adjustable: "+n22.adjustable);
System.out.println("Stones: "+n22.stones);
System.out.println("Type: "+n22.type);
System.out.println("Origin: "+n22.origin);
System.out.println("Finish: "+n22.finish);
System.out.println("Style: "+n22.style);
System.out.println("Gender: "+n22.gender);
System.out.println("Clasp Type: "+n22.claspType);
System.out.println("Plating: "+n22.plating);
System.out.println("Durability: "+n22.durability);
System.out.println("Usage: "+n22.usage);
System.out.println("Warranty: "+n22.warranty);
System.out.println("Manufacturer: "+n22.manufacturer+"\n");


Necklace n23=new Necklace();
n23.brand="PC Jeweller";
n23.color="Silver";
n23.material="Silver";
n23.price=32000;
n23.weight=22;
n23.size="Medium";
n23.design="Star";
n23.adjustable=true;
n23.stones=9;
n23.type="Chain";
n23.origin="India";
n23.finish="Matte";
n23.style="Modern";
n23.gender="Female";
n23.claspType="Hook";
n23.plating="Silver";
n23.durability="Medium";
n23.usage="Daily";
n23.warranty="1 year";
n23.manufacturer="PC Jeweller";

System.out.println("Brand: "+n23.brand);
System.out.println("Color: "+n23.color);
System.out.println("Material: "+n23.material);
System.out.println("Price: "+n23.price);
System.out.println("Weight: "+n23.weight);
System.out.println("Size: "+n23.size);
System.out.println("Design: "+n23.design);
System.out.println("Adjustable: "+n23.adjustable);
System.out.println("Stones: "+n23.stones);
System.out.println("Type: "+n23.type);
System.out.println("Origin: "+n23.origin);
System.out.println("Finish: "+n23.finish);
System.out.println("Style: "+n23.style);
System.out.println("Gender: "+n23.gender);
System.out.println("Clasp Type: "+n23.claspType);
System.out.println("Plating: "+n23.plating);
System.out.println("Durability: "+n23.durability);
System.out.println("Usage: "+n23.usage);
System.out.println("Warranty: "+n23.warranty);
System.out.println("Manufacturer: "+n23.manufacturer+"\n");


Necklace n24=new Necklace();
n24.brand="Tanishq";
n24.color="Gold";
n24.material="Gold";
n24.price=60000;
n24.weight=31;
n24.size="Long";
n24.design="Floral";
n24.adjustable=false;
n24.stones=17;
n24.type="Chain";
n24.origin="India";
n24.finish="Glossy";
n24.style="Traditional";
n24.gender="Female";
n24.claspType="Lock";
n24.plating="Gold";
n24.durability="High";
n24.usage="Wedding";
n24.warranty="3 years";
n24.manufacturer="Tanishq Ltd";

System.out.println("Brand: "+n24.brand);
System.out.println("Color: "+n24.color);
System.out.println("Material: "+n24.material);
System.out.println("Price: "+n24.price);
System.out.println("Weight: "+n24.weight);
System.out.println("Size: "+n24.size);
System.out.println("Design: "+n24.design);
System.out.println("Adjustable: "+n24.adjustable);
System.out.println("Stones: "+n24.stones);
System.out.println("Type: "+n24.type);
System.out.println("Origin: "+n24.origin);
System.out.println("Finish: "+n24.finish);
System.out.println("Style: "+n24.style);
System.out.println("Gender: "+n24.gender);
System.out.println("Clasp Type: "+n24.claspType);
System.out.println("Plating: "+n24.plating);
System.out.println("Durability: "+n24.durability);
System.out.println("Usage: "+n24.usage);
System.out.println("Warranty: "+n24.warranty);
System.out.println("Manufacturer: "+n24.manufacturer+"\n");


Necklace n25=new Necklace();
n25.brand="Kalyan";
n25.color="Rose Gold";
n25.material="Gold";
n25.price=52000;
n25.weight=27;
n25.size="Long";
n25.design="Heart";
n25.adjustable=true;
n25.stones=13;
n25.type="Chain";
n25.origin="India";
n25.finish="Glossy";
n25.style="Modern";
n25.gender="Female";
n25.claspType="Hook";
n25.plating="Rose Gold";
n25.durability="High";
n25.usage="Casual";
n25.warranty="2 years";
n25.manufacturer="Kalyan Jewellers";

System.out.println("Brand: "+n25.brand);
System.out.println("Color: "+n25.color);
System.out.println("Material: "+n25.material);
System.out.println("Price: "+n25.price);
System.out.println("Weight: "+n25.weight);
System.out.println("Size: "+n25.size);
System.out.println("Design: "+n25.design);
System.out.println("Adjustable: "+n25.adjustable);
System.out.println("Stones: "+n25.stones);
System.out.println("Type: "+n25.type);
System.out.println("Origin: "+n25.origin);
System.out.println("Finish: "+n25.finish);
System.out.println("Style: "+n25.style);
System.out.println("Gender: "+n25.gender);
System.out.println("Clasp Type: "+n25.claspType);
System.out.println("Plating: "+n25.plating);
System.out.println("Durability: "+n25.durability);
System.out.println("Usage: "+n25.usage);
System.out.println("Warranty: "+n25.warranty);
System.out.println("Manufacturer: "+n25.manufacturer+"\n");


		// Parameterized constructor objects

		Necklace nr1=new Necklace("Tanishq","Gold","Gold",50000,25,"Long","Floral",true,10,"Chain","India","Glossy","Traditional","Female","Hook","Gold","High","Wedding","2 years","Tanishq Ltd");

System.out.println("Brand: "+nr1.brand);
System.out.println("Color: "+nr1.color);
System.out.println("Material: "+nr1.material);
System.out.println("Price: "+nr1.price);
System.out.println("Weight: "+nr1.weight);
System.out.println("Size: "+nr1.size);
System.out.println("Design: "+nr1.design);
System.out.println("Adjustable: "+nr1.adjustable);
System.out.println("Stones: "+nr1.stones);
System.out.println("Type: "+nr1.type);
System.out.println("Origin: "+nr1.origin);
System.out.println("Finish: "+nr1.finish);
System.out.println("Style: "+nr1.style);
System.out.println("Gender: "+nr1.gender);
System.out.println("Clasp Type: "+nr1.claspType);
System.out.println("Plating: "+nr1.plating);
System.out.println("Durability: "+nr1.durability);
System.out.println("Usage: "+nr1.usage);
System.out.println("Warranty: "+nr1.warranty);
System.out.println("Manufacturer: "+nr1.manufacturer+"\n");


Necklace nr2=new Necklace("Malabar","Silver","Silver",30000,20,"Medium","Leaf",true,6,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");

System.out.println("Brand: "+nr2.brand);
System.out.println("Color: "+nr2.color);
System.out.println("Material: "+nr2.material);
System.out.println("Price: "+nr2.price);
System.out.println("Weight: "+nr2.weight);
System.out.println("Size: "+nr2.size);
System.out.println("Design: "+nr2.design);
System.out.println("Adjustable: "+nr2.adjustable);
System.out.println("Stones: "+nr2.stones);
System.out.println("Type: "+nr2.type);
System.out.println("Origin: "+nr2.origin);
System.out.println("Finish: "+nr2.finish);
System.out.println("Style: "+nr2.style);
System.out.println("Gender: "+nr2.gender);
System.out.println("Clasp Type: "+nr2.claspType);
System.out.println("Plating: "+nr2.plating);
System.out.println("Durability: "+nr2.durability);
System.out.println("Usage: "+nr2.usage);
System.out.println("Warranty: "+nr2.warranty);
System.out.println("Manufacturer: "+nr2.manufacturer+"\n");


Necklace nr3=new Necklace("Kalyan","Rose Gold","Gold",45000,22,"Long","Heart",true,8,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr3.brand);
System.out.println("Color: "+nr3.color);
System.out.println("Material: "+nr3.material);
System.out.println("Price: "+nr3.price);
System.out.println("Weight: "+nr3.weight);
System.out.println("Size: "+nr3.size);
System.out.println("Design: "+nr3.design);
System.out.println("Adjustable: "+nr3.adjustable);
System.out.println("Stones: "+nr3.stones);
System.out.println("Type: "+nr3.type);
System.out.println("Origin: "+nr3.origin);
System.out.println("Finish: "+nr3.finish);
System.out.println("Style: "+nr3.style);
System.out.println("Gender: "+nr3.gender);
System.out.println("Clasp Type: "+nr3.claspType);
System.out.println("Plating: "+nr3.plating);
System.out.println("Durability: "+nr3.durability);
System.out.println("Usage: "+nr3.usage);
System.out.println("Warranty: "+nr3.warranty);
System.out.println("Manufacturer: "+nr3.manufacturer+"\n");


Necklace nr4=new Necklace("PC Jeweller","Silver","Silver",28000,18,"Medium","Star",true,5,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Daily","1 year","PC Jeweller");

System.out.println("Brand: "+nr4.brand);
System.out.println("Color: "+nr4.color);
System.out.println("Material: "+nr4.material);
System.out.println("Price: "+nr4.price);
System.out.println("Weight: "+nr4.weight);
System.out.println("Size: "+nr4.size);
System.out.println("Design: "+nr4.design);
System.out.println("Adjustable: "+nr4.adjustable);
System.out.println("Stones: "+nr4.stones);
System.out.println("Type: "+nr4.type);
System.out.println("Origin: "+nr4.origin);
System.out.println("Finish: "+nr4.finish);
System.out.println("Style: "+nr4.style);
System.out.println("Gender: "+nr4.gender);
System.out.println("Clasp Type: "+nr4.claspType);
System.out.println("Plating: "+nr4.plating);
System.out.println("Durability: "+nr4.durability);
System.out.println("Usage: "+nr4.usage);
System.out.println("Warranty: "+nr4.warranty);
System.out.println("Manufacturer: "+nr4.manufacturer+"\n");


Necklace nr5=new Necklace("Tanishq","Gold","Gold",52000,26,"Long","Floral",false,12,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");

System.out.println("Brand: "+nr5.brand);
System.out.println("Color: "+nr5.color);
System.out.println("Material: "+nr5.material);
System.out.println("Price: "+nr5.price);
System.out.println("Weight: "+nr5.weight);
System.out.println("Size: "+nr5.size);
System.out.println("Design: "+nr5.design);
System.out.println("Adjustable: "+nr5.adjustable);
System.out.println("Stones: "+nr5.stones);
System.out.println("Type: "+nr5.type);
System.out.println("Origin: "+nr5.origin);
System.out.println("Finish: "+nr5.finish);
System.out.println("Style: "+nr5.style);
System.out.println("Gender: "+nr5.gender);
System.out.println("Clasp Type: "+nr5.claspType);
System.out.println("Plating: "+nr5.plating);
System.out.println("Durability: "+nr5.durability);
System.out.println("Usage: "+nr5.usage);
System.out.println("Warranty: "+nr5.warranty);
System.out.println("Manufacturer: "+nr5.manufacturer+"\n");

Necklace nr6=new Necklace("Malabar","Silver","Silver",32000,21,"Medium","Leaf",true,7,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");
System.out.println("Brand: "+nr6.brand);
System.out.println("Color: "+nr6.color);
System.out.println("Material: "+nr6.material);
System.out.println("Price: "+nr6.price);
System.out.println("Weight: "+nr6.weight);
System.out.println("Size: "+nr6.size);
System.out.println("Design: "+nr6.design);
System.out.println("Adjustable: "+nr6.adjustable);
System.out.println("Stones: "+nr6.stones);
System.out.println("Type: "+nr6.type);
System.out.println("Origin: "+nr6.origin);
System.out.println("Finish: "+nr6.finish);
System.out.println("Style: "+nr6.style);
System.out.println("Gender: "+nr6.gender);
System.out.println("Clasp Type: "+nr6.claspType);
System.out.println("Plating: "+nr6.plating);
System.out.println("Durability: "+nr6.durability);
System.out.println("Usage: "+nr6.usage);
System.out.println("Warranty: "+nr6.warranty);
System.out.println("Manufacturer: "+nr6.manufacturer+"\n");


Necklace nr7=new Necklace("Kalyan","Rose Gold","Gold",47000,23,"Long","Heart",true,9,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");
System.out.println("Brand: "+nr7.brand);
System.out.println("Color: "+nr7.color);
System.out.println("Material: "+nr7.material);
System.out.println("Price: "+nr7.price);
System.out.println("Weight: "+nr7.weight);
System.out.println("Size: "+nr7.size);
System.out.println("Design: "+nr7.design);
System.out.println("Adjustable: "+nr7.adjustable);
System.out.println("Stones: "+nr7.stones);
System.out.println("Type: "+nr7.type);
System.out.println("Origin: "+nr7.origin);
System.out.println("Finish: "+nr7.finish);
System.out.println("Style: "+nr7.style);
System.out.println("Gender: "+nr7.gender);
System.out.println("Clasp Type: "+nr7.claspType);
System.out.println("Plating: "+nr7.plating);
System.out.println("Durability: "+nr7.durability);
System.out.println("Usage: "+nr7.usage);
System.out.println("Warranty: "+nr7.warranty);
System.out.println("Manufacturer: "+nr7.manufacturer+"\n");


Necklace nr8=new Necklace("PC Jeweller","Silver","Silver",29000,19,"Medium","Star",true,6,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Daily","1 year","PC Jeweller");
System.out.println("Brand: "+nr8.brand);
System.out.println("Color: "+nr8.color);
System.out.println("Material: "+nr8.material);
System.out.println("Price: "+nr8.price);
System.out.println("Weight: "+nr8.weight);
System.out.println("Size: "+nr8.size);
System.out.println("Design: "+nr8.design);
System.out.println("Adjustable: "+nr8.adjustable);
System.out.println("Stones: "+nr8.stones);
System.out.println("Type: "+nr8.type);
System.out.println("Origin: "+nr8.origin);
System.out.println("Finish: "+nr8.finish);
System.out.println("Style: "+nr8.style);
System.out.println("Gender: "+nr8.gender);
System.out.println("Clasp Type: "+nr8.claspType);
System.out.println("Plating: "+nr8.plating);
System.out.println("Durability: "+nr8.durability);
System.out.println("Usage: "+nr8.usage);
System.out.println("Warranty: "+nr8.warranty);
System.out.println("Manufacturer: "+nr8.manufacturer+"\n");


Necklace nr9=new Necklace("Tanishq","Gold","Gold",54000,27,"Long","Floral",false,13,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");
System.out.println("Brand: "+nr9.brand);
System.out.println("Color: "+nr9.color);
System.out.println("Material: "+nr9.material);
System.out.println("Price: "+nr9.price);
System.out.println("Weight: "+nr9.weight);
System.out.println("Size: "+nr9.size);
System.out.println("Design: "+nr9.design);
System.out.println("Adjustable: "+nr9.adjustable);
System.out.println("Stones: "+nr9.stones);
System.out.println("Type: "+nr9.type);
System.out.println("Origin: "+nr9.origin);
System.out.println("Finish: "+nr9.finish);
System.out.println("Style: "+nr9.style);
System.out.println("Gender: "+nr9.gender);
System.out.println("Clasp Type: "+nr9.claspType);
System.out.println("Plating: "+nr9.plating);
System.out.println("Durability: "+nr9.durability);
System.out.println("Usage: "+nr9.usage);
System.out.println("Warranty: "+nr9.warranty);
System.out.println("Manufacturer: "+nr9.manufacturer+"\n");


Necklace nr10=new Necklace("Malabar","Silver","Silver",34000,22,"Medium","Leaf",true,8,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");
System.out.println("Brand: "+nr10.brand);
System.out.println("Color: "+nr10.color);
System.out.println("Material: "+nr10.material);
System.out.println("Price: "+nr10.price);
System.out.println("Weight: "+nr10.weight);
System.out.println("Size: "+nr10.size);
System.out.println("Design: "+nr10.design);
System.out.println("Adjustable: "+nr10.adjustable);
System.out.println("Stones: "+nr10.stones);
System.out.println("Type: "+nr10.type);
System.out.println("Origin: "+nr10.origin);
System.out.println("Finish: "+nr10.finish);
System.out.println("Style: "+nr10.style);
System.out.println("Gender: "+nr10.gender);
System.out.println("Clasp Type: "+nr10.claspType);
System.out.println("Plating: "+nr10.plating);
System.out.println("Durability: "+nr10.durability);
System.out.println("Usage: "+nr10.usage);
System.out.println("Warranty: "+nr10.warranty);
System.out.println("Manufacturer: "+nr10.manufacturer+"\n");

Necklace nr11=new Necklace("Kalyan","Rose Gold","Gold",46000,23,"Long","Heart",true,9,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr11.brand);
System.out.println("Color: "+nr11.color);
System.out.println("Material: "+nr11.material);
System.out.println("Price: "+nr11.price);
System.out.println("Weight: "+nr11.weight);
System.out.println("Size: "+nr11.size);
System.out.println("Design: "+nr11.design);
System.out.println("Adjustable: "+nr11.adjustable);
System.out.println("Stones: "+nr11.stones);
System.out.println("Type: "+nr11.type);
System.out.println("Origin: "+nr11.origin);
System.out.println("Finish: "+nr11.finish);
System.out.println("Style: "+nr11.style);
System.out.println("Gender: "+nr11.gender);
System.out.println("Clasp Type: "+nr11.claspType);
System.out.println("Plating: "+nr11.plating);
System.out.println("Durability: "+nr11.durability);
System.out.println("Usage: "+nr11.usage);
System.out.println("Warranty: "+nr11.warranty);
System.out.println("Manufacturer: "+nr11.manufacturer+"\n");


Necklace nr12=new Necklace("PC Jeweller","Silver","Silver",30000,20,"Medium","Star",true,7,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Daily","1 year","PC Jeweller");

System.out.println("Brand: "+nr12.brand);
System.out.println("Color: "+nr12.color);
System.out.println("Material: "+nr12.material);
System.out.println("Price: "+nr12.price);
System.out.println("Weight: "+nr12.weight);
System.out.println("Size: "+nr12.size);
System.out.println("Design: "+nr12.design);
System.out.println("Adjustable: "+nr12.adjustable);
System.out.println("Stones: "+nr12.stones);
System.out.println("Type: "+nr12.type);
System.out.println("Origin: "+nr12.origin);
System.out.println("Finish: "+nr12.finish);
System.out.println("Style: "+nr12.style);
System.out.println("Gender: "+nr12.gender);
System.out.println("Clasp Type: "+nr12.claspType);
System.out.println("Plating: "+nr12.plating);
System.out.println("Durability: "+nr12.durability);
System.out.println("Usage: "+nr12.usage);
System.out.println("Warranty: "+nr12.warranty);
System.out.println("Manufacturer: "+nr12.manufacturer+"\n");


Necklace nr13=new Necklace("Tanishq","Gold","Gold",55000,28,"Long","Floral",false,14,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");

System.out.println("Brand: "+nr13.brand);
System.out.println("Color: "+nr13.color);
System.out.println("Material: "+nr13.material);
System.out.println("Price: "+nr13.price);
System.out.println("Weight: "+nr13.weight);
System.out.println("Size: "+nr13.size);
System.out.println("Design: "+nr13.design);
System.out.println("Adjustable: "+nr13.adjustable);
System.out.println("Stones: "+nr13.stones);
System.out.println("Type: "+nr13.type);
System.out.println("Origin: "+nr13.origin);
System.out.println("Finish: "+nr13.finish);
System.out.println("Style: "+nr13.style);
System.out.println("Gender: "+nr13.gender);
System.out.println("Clasp Type: "+nr13.claspType);
System.out.println("Plating: "+nr13.plating);
System.out.println("Durability: "+nr13.durability);
System.out.println("Usage: "+nr13.usage);
System.out.println("Warranty: "+nr13.warranty);
System.out.println("Manufacturer: "+nr13.manufacturer+"\n");


Necklace nr14=new Necklace("Malabar","Silver","Silver",33000,21,"Medium","Leaf",true,8,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");

System.out.println("Brand: "+nr14.brand);
System.out.println("Color: "+nr14.color);
System.out.println("Material: "+nr14.material);
System.out.println("Price: "+nr14.price);
System.out.println("Weight: "+nr14.weight);
System.out.println("Size: "+nr14.size);
System.out.println("Design: "+nr14.design);
System.out.println("Adjustable: "+nr14.adjustable);
System.out.println("Stones: "+nr14.stones);
System.out.println("Type: "+nr14.type);
System.out.println("Origin: "+nr14.origin);
System.out.println("Finish: "+nr14.finish);
System.out.println("Style: "+nr14.style);
System.out.println("Gender: "+nr14.gender);
System.out.println("Clasp Type: "+nr14.claspType);
System.out.println("Plating: "+nr14.plating);
System.out.println("Durability: "+nr14.durability);
System.out.println("Usage: "+nr14.usage);
System.out.println("Warranty: "+nr14.warranty);
System.out.println("Manufacturer: "+nr14.manufacturer+"\n");


Necklace nr15=new Necklace("Kalyan","Rose Gold","Gold",48000,24,"Long","Heart",true,10,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr15.brand);
System.out.println("Color: "+nr15.color);
System.out.println("Material: "+nr15.material);
System.out.println("Price: "+nr15.price);
System.out.println("Weight: "+nr15.weight);
System.out.println("Size: "+nr15.size);
System.out.println("Design: "+nr15.design);
System.out.println("Adjustable: "+nr15.adjustable);
System.out.println("Stones: "+nr15.stones);
System.out.println("Type: "+nr15.type);
System.out.println("Origin: "+nr15.origin);
System.out.println("Finish: "+nr15.finish);
System.out.println("Style: "+nr15.style);
System.out.println("Gender: "+nr15.gender);
System.out.println("Clasp Type: "+nr15.claspType);
System.out.println("Plating: "+nr15.plating);
System.out.println("Durability: "+nr15.durability);
System.out.println("Usage: "+nr15.usage);
System.out.println("Warranty: "+nr15.warranty);
System.out.println("Manufacturer: "+nr15.manufacturer+"\n");

Necklace nr16=new Necklace("PC Jeweller","Silver","Silver",31000,21,"Medium","Star",true,6,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Daily","1 year","PC Jeweller");

System.out.println("Brand: "+nr16.brand);
System.out.println("Color: "+nr16.color);
System.out.println("Material: "+nr16.material);
System.out.println("Price: "+nr16.price);
System.out.println("Weight: "+nr16.weight);
System.out.println("Size: "+nr16.size);
System.out.println("Design: "+nr16.design);
System.out.println("Adjustable: "+nr16.adjustable);
System.out.println("Stones: "+nr16.stones);
System.out.println("Type: "+nr16.type);
System.out.println("Origin: "+nr16.origin);
System.out.println("Finish: "+nr16.finish);
System.out.println("Style: "+nr16.style);
System.out.println("Gender: "+nr16.gender);
System.out.println("Clasp Type: "+nr16.claspType);
System.out.println("Plating: "+nr16.plating);
System.out.println("Durability: "+nr16.durability);
System.out.println("Usage: "+nr16.usage);
System.out.println("Warranty: "+nr16.warranty);
System.out.println("Manufacturer: "+nr16.manufacturer+"\n");


Necklace nr17=new Necklace("Tanishq","Gold","Gold",56000,29,"Long","Floral",false,15,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");

System.out.println("Brand: "+nr17.brand);
System.out.println("Color: "+nr17.color);
System.out.println("Material: "+nr17.material);
System.out.println("Price: "+nr17.price);
System.out.println("Weight: "+nr17.weight);
System.out.println("Size: "+nr17.size);
System.out.println("Design: "+nr17.design);
System.out.println("Adjustable: "+nr17.adjustable);
System.out.println("Stones: "+nr17.stones);
System.out.println("Type: "+nr17.type);
System.out.println("Origin: "+nr17.origin);
System.out.println("Finish: "+nr17.finish);
System.out.println("Style: "+nr17.style);
System.out.println("Gender: "+nr17.gender);
System.out.println("Clasp Type: "+nr17.claspType);
System.out.println("Plating: "+nr17.plating);
System.out.println("Durability: "+nr17.durability);
System.out.println("Usage: "+nr17.usage);
System.out.println("Warranty: "+nr17.warranty);
System.out.println("Manufacturer: "+nr17.manufacturer+"\n");


Necklace nr18=new Necklace("Malabar","Silver","Silver",35000,23,"Medium","Leaf",true,9,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");

System.out.println("Brand: "+nr18.brand);
System.out.println("Color: "+nr18.color);
System.out.println("Material: "+nr18.material);
System.out.println("Price: "+nr18.price);
System.out.println("Weight: "+nr18.weight);
System.out.println("Size: "+nr18.size);
System.out.println("Design: "+nr18.design);
System.out.println("Adjustable: "+nr18.adjustable);
System.out.println("Stones: "+nr18.stones);
System.out.println("Type: "+nr18.type);
System.out.println("Origin: "+nr18.origin);
System.out.println("Finish: "+nr18.finish);
System.out.println("Style: "+nr18.style);
System.out.println("Gender: "+nr18.gender);
System.out.println("Clasp Type: "+nr18.claspType);
System.out.println("Plating: "+nr18.plating);
System.out.println("Durability: "+nr18.durability);
System.out.println("Usage: "+nr18.usage);
System.out.println("Warranty: "+nr18.warranty);
System.out.println("Manufacturer: "+nr18.manufacturer+"\n");


Necklace nr19=new Necklace("Kalyan","Rose Gold","Gold",49000,25,"Long","Heart",true,11,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr19.brand);
System.out.println("Color: "+nr19.color);
System.out.println("Material: "+nr19.material);
System.out.println("Price: "+nr19.price);
System.out.println("Weight: "+nr19.weight);
System.out.println("Size: "+nr19.size);
System.out.println("Design: "+nr19.design);
System.out.println("Adjustable: "+nr19.adjustable);
System.out.println("Stones: "+nr19.stones);
System.out.println("Type: "+nr19.type);
System.out.println("Origin: "+nr19.origin);
System.out.println("Finish: "+nr19.finish);
System.out.println("Style: "+nr19.style);
System.out.println("Gender: "+nr19.gender);
System.out.println("Clasp Type: "+nr19.claspType);
System.out.println("Plating: "+nr19.plating);
System.out.println("Durability: "+nr19.durability);
System.out.println("Usage: "+nr19.usage);
System.out.println("Warranty: "+nr19.warranty);
System.out.println("Manufacturer: "+nr19.manufacturer+"\n");


Necklace nr20=new Necklace("Tanishq","Gold","Gold",58000,30,"Long","Floral",false,16,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");

System.out.println("Brand: "+nr20.brand);
System.out.println("Color: "+nr20.color);
System.out.println("Material: "+nr20.material);
System.out.println("Price: "+nr20.price);
System.out.println("Weight: "+nr20.weight);
System.out.println("Size: "+nr20.size);
System.out.println("Design: "+nr20.design);
System.out.println("Adjustable: "+nr20.adjustable);
System.out.println("Stones: "+nr20.stones);
System.out.println("Type: "+nr20.type);
System.out.println("Origin: "+nr20.origin);
System.out.println("Finish: "+nr20.finish);
System.out.println("Style: "+nr20.style);
System.out.println("Gender: "+nr20.gender);
System.out.println("Clasp Type: "+nr20.claspType);
System.out.println("Plating: "+nr20.plating);
System.out.println("Durability: "+nr20.durability);
System.out.println("Usage: "+nr20.usage);
System.out.println("Warranty: "+nr20.warranty);
System.out.println("Manufacturer: "+nr20.manufacturer+"\n");

Necklace nr21=new Necklace("Malabar","Silver","Silver",36000,24,"Medium","Leaf",true,10,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Party","1 year","Malabar Ltd");

System.out.println("Brand: "+nr21.brand);
System.out.println("Color: "+nr21.color);
System.out.println("Material: "+nr21.material);
System.out.println("Price: "+nr21.price);
System.out.println("Weight: "+nr21.weight);
System.out.println("Size: "+nr21.size);
System.out.println("Design: "+nr21.design);
System.out.println("Adjustable: "+nr21.adjustable);
System.out.println("Stones: "+nr21.stones);
System.out.println("Type: "+nr21.type);
System.out.println("Origin: "+nr21.origin);
System.out.println("Finish: "+nr21.finish);
System.out.println("Style: "+nr21.style);
System.out.println("Gender: "+nr21.gender);
System.out.println("Clasp Type: "+nr21.claspType);
System.out.println("Plating: "+nr21.plating);
System.out.println("Durability: "+nr21.durability);
System.out.println("Usage: "+nr21.usage);
System.out.println("Warranty: "+nr21.warranty);
System.out.println("Manufacturer: "+nr21.manufacturer+"\n");


Necklace nr22=new Necklace("Kalyan","Rose Gold","Gold",50000,26,"Long","Heart",true,12,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr22.brand);
System.out.println("Color: "+nr22.color);
System.out.println("Material: "+nr22.material);
System.out.println("Price: "+nr22.price);
System.out.println("Weight: "+nr22.weight);
System.out.println("Size: "+nr22.size);
System.out.println("Design: "+nr22.design);
System.out.println("Adjustable: "+nr22.adjustable);
System.out.println("Stones: "+nr22.stones);
System.out.println("Type: "+nr22.type);
System.out.println("Origin: "+nr22.origin);
System.out.println("Finish: "+nr22.finish);
System.out.println("Style: "+nr22.style);
System.out.println("Gender: "+nr22.gender);
System.out.println("Clasp Type: "+nr22.claspType);
System.out.println("Plating: "+nr22.plating);
System.out.println("Durability: "+nr22.durability);
System.out.println("Usage: "+nr22.usage);
System.out.println("Warranty: "+nr22.warranty);
System.out.println("Manufacturer: "+nr22.manufacturer+"\n");


Necklace nr23=new Necklace("PC Jeweller","Silver","Silver",32000,22,"Medium","Star",true,9,"Chain","India","Matte","Modern","Female","Hook","Silver","Medium","Daily","1 year","PC Jeweller");

System.out.println("Brand: "+nr23.brand);
System.out.println("Color: "+nr23.color);
System.out.println("Material: "+nr23.material);
System.out.println("Price: "+nr23.price);
System.out.println("Weight: "+nr23.weight);
System.out.println("Size: "+nr23.size);
System.out.println("Design: "+nr23.design);
System.out.println("Adjustable: "+nr23.adjustable);
System.out.println("Stones: "+nr23.stones);
System.out.println("Type: "+nr23.type);
System.out.println("Origin: "+nr23.origin);
System.out.println("Finish: "+nr23.finish);
System.out.println("Style: "+nr23.style);
System.out.println("Gender: "+nr23.gender);
System.out.println("Clasp Type: "+nr23.claspType);
System.out.println("Plating: "+nr23.plating);
System.out.println("Durability: "+nr23.durability);
System.out.println("Usage: "+nr23.usage);
System.out.println("Warranty: "+nr23.warranty);
System.out.println("Manufacturer: "+nr23.manufacturer+"\n");


Necklace nr24=new Necklace("Tanishq","Gold","Gold",60000,31,"Long","Floral",false,17,"Chain","India","Glossy","Traditional","Female","Lock","Gold","High","Wedding","3 years","Tanishq Ltd");

System.out.println("Brand: "+nr24.brand);
System.out.println("Color: "+nr24.color);
System.out.println("Material: "+nr24.material);
System.out.println("Price: "+nr24.price);
System.out.println("Weight: "+nr24.weight);
System.out.println("Size: "+nr24.size);
System.out.println("Design: "+nr24.design);
System.out.println("Adjustable: "+nr24.adjustable);
System.out.println("Stones: "+nr24.stones);
System.out.println("Type: "+nr24.type);
System.out.println("Origin: "+nr24.origin);
System.out.println("Finish: "+nr24.finish);
System.out.println("Style: "+nr24.style);
System.out.println("Gender: "+nr24.gender);
System.out.println("Clasp Type: "+nr24.claspType);
System.out.println("Plating: "+nr24.plating);
System.out.println("Durability: "+nr24.durability);
System.out.println("Usage: "+nr24.usage);
System.out.println("Warranty: "+nr24.warranty);
System.out.println("Manufacturer: "+nr24.manufacturer+"\n");


Necklace nr25=new Necklace("Kalyan","Rose Gold","Gold",52000,27,"Long","Heart",true,13,"Chain","India","Glossy","Modern","Female","Hook","Rose Gold","High","Casual","2 years","Kalyan Jewellers");

System.out.println("Brand: "+nr25.brand);
System.out.println("Color: "+nr25.color);
System.out.println("Material: "+nr25.material);
System.out.println("Price: "+nr25.price);
System.out.println("Weight: "+nr25.weight);
System.out.println("Size: "+nr25.size);
System.out.println("Design: "+nr25.design);
System.out.println("Adjustable: "+nr25.adjustable);
System.out.println("Stones: "+nr25.stones);
System.out.println("Type: "+nr25.type);
System.out.println("Origin: "+nr25.origin);
System.out.println("Finish: "+nr25.finish);
System.out.println("Style: "+nr25.style);
System.out.println("Gender: "+nr25.gender);
System.out.println("Clasp Type: "+nr25.claspType);
System.out.println("Plating: "+nr25.plating);
System.out.println("Durability: "+nr25.durability);
System.out.println("Usage: "+nr25.usage);
System.out.println("Warranty: "+nr25.warranty);
System.out.println("Manufacturer: "+nr25.manufacturer+"\n");

	}
}